
package Viwe;


import Model.DBconect;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import net.proteanit.sql.DbUtils;
 
public class test extends javax.swing.JFrame {


    Connection conn = null;
    PreparedStatment pst = null;
    JTable test;
    ResultSet rs=null;
   
    
        
     
    
    public test() {
        this.rs = null;
        initComponents();
        conn = DBconect.connect();
                dataloadone();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tselect = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        tindex = new javax.swing.JTextField();
        tbest = new javax.swing.JTextField();
        tname = new javax.swing.JTextField();
        tmatch = new javax.swing.JTextField();
        trun = new javax.swing.JTextField();
        twickets = new javax.swing.JTextField();
        tjurscy = new javax.swing.JTextField();
        tstrike = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        move = new javax.swing.JButton();
        jButton27 = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        tavg = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setBackground(new java.awt.Color(204, 255, 204));
        jButton2.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(51, 0, 204));
        jButton2.setText("ODI");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 60, 110, -1));

        jButton3.setBackground(new java.awt.Color(204, 255, 204));
        jButton3.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(51, 0, 204));
        jButton3.setText("T20");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 60, 110, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("ENTER PLAYER NAME");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 200, 30));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText("INDEX NUMBER");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 180, 30));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("SELECT YOUR FROMAT");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 230, -1));

        tselect.setBackground(new java.awt.Color(255, 0, 204));
        tselect.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        tselect.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECT", "BATSMAN", "BOWLLER", "ALLROUNDER" }));
        jPanel1.add(tselect, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, 130, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setText("MATCHES");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 170, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setText("RUNS");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 120, 20));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel8.setText("WICKETS");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, -1, -1));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel9.setText("JURSCY NUMBER");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 160, -1));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel10.setText("STRIKE RATE");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 150, -1));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel12.setText("AVARAGE");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, 90, -1));

        tindex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tindexActionPerformed(evt);
            }
        });
        jPanel1.add(tindex, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, 150, -1));

        tbest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbestActionPerformed(evt);
            }
        });
        jPanel1.add(tbest, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 450, 150, -1));

        tname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tnameActionPerformed(evt);
            }
        });
        jPanel1.add(tname, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 130, 150, -1));

        tmatch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tmatchActionPerformed(evt);
            }
        });
        jPanel1.add(tmatch, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, 150, -1));

        trun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trunActionPerformed(evt);
            }
        });
        jPanel1.add(trun, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 270, 150, -1));

        twickets.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twicketsActionPerformed(evt);
            }
        });
        jPanel1.add(twickets, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 300, 150, -1));

        tjurscy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tjurscyActionPerformed(evt);
            }
        });
        jPanel1.add(tjurscy, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 340, 150, -1));

        tstrike.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tstrikeActionPerformed(evt);
            }
        });
        jPanel1.add(tstrike, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 380, 150, -1));

        jPanel2.setBackground(new java.awt.Color(102, 102, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tableMouseEntered(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 720, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 110, 900, 240));

        move.setBackground(new java.awt.Color(255, 255, 255));
        move.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        move.setText("SUBMIT");
        move.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moveActionPerformed(evt);
            }
        });
        jPanel1.add(move, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 550, -1, -1));

        jButton27.setBackground(new java.awt.Color(0, 0, 153));
        jButton27.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton27.setText("UPDATE");
        jButton27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton27ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton27, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 550, -1, -1));

        jButton28.setBackground(new java.awt.Color(255, 255, 255));
        jButton28.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton28.setText("DELETE");
        jButton28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton28ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton28, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 550, -1, -1));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel11.setText("BEST");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 450, 80, 40));

        tavg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tavgActionPerformed(evt);
            }
        });
        jPanel1.add(tavg, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 420, 150, -1));

        jPanel3.setBackground(new java.awt.Color(0, 0, 204));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("HC CRICKET DETAILS FORM");
        jPanel3.add(jLabel6);

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1470, 50));

        jPanel4.setBackground(new java.awt.Color(153, 153, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel18.setBackground(new java.awt.Color(153, 51, 0));
        jLabel18.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(51, 51, 0));
        jLabel18.setText("TEST CRICKET");
        jPanel4.add(jLabel18);

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 440, 550));

        jPanel5.setBackground(new java.awt.Color(0, 0, 153));
        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 600, 1460, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/folder/sri lanka.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 380, 180, 170));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/folder/images123-removebg-preview.png"))); // NOI18N
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 390, 200, 150));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/folder/sss.png"))); // NOI18N
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 420, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1500, 640));

        setSize(new java.awt.Dimension(1362, 684));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
      
    
     public  void dataloadone(){
    
        try { 
            String sql ="SELECT playername, indexnumber, role, matches, runs, wickets, jurscynubmer, strikerate, avarage, best FROM testcricket";
             PreparedStatement pst = conn.prepareStatement(sql);
             rs = (ResultSet) pst.executeQuery();
            table.setModel(DbUtils.resultSetToTableModel(rs));
        
        } catch (Exception e) {
             JOptionPane.showMessageDialog(null, e.getMessage());
        }
 
    }
    public void testdata(){
 
       int selectedRow = table.getSelectedRow();
    
    // Ensure a row is selected
    if (selectedRow == -1) {
        // No row is selected, handle this case
        System.out.println("No row selected");
        return;
    }
    
    // Retrieve and store values from the selected row
    String name = table.getValueAt(selectedRow, 0).toString();
    String index = table.getValueAt(selectedRow, 1).toString();
    String select = table.getValueAt(selectedRow, 2).toString();
    String match = table.getValueAt(selectedRow, 3).toString();
    String runs = table.getValueAt(selectedRow, 4).toString();
    String wickets = table.getValueAt(selectedRow, 5).toString();
    String jn = table.getValueAt(selectedRow, 6).toString();
    String status = table.getValueAt(selectedRow, 7).toString();
    String average = table.getValueAt(selectedRow, 8).toString();
    String best = table.getValueAt(selectedRow, 9).toString();
    
    
    tname.setText(name);
    tindex.setText(index);
    tselect.setSelectedItem(select);
    tmatch.setText(match);
    trun.setText(runs);
    twickets.setText(wickets);
    tjurscy.setText(jn);
    tstrike.setText(status);
    tavg.setText(average);
    tbest.setText(best);
     
       
    }
    private void tabaledatat() {
String name = tname.getText();
String index = tindex.getText();
String role = tselect.getSelectedItem().toString();
String match = tmatch.getText();
String run = trun.getText();
String wicket = twickets.getText();
String js = tjurscy.getText();
String sr = tstrike.getText();
String avg = tavg.getText();
String best = tbest.getText();

PreparedStatement pst = null;
ResultSet rs = null;

try {
    // Check if the record exists before attempting the update
    String checkSql = "SELECT COUNT(*) FROM testcricket WHERE indexnumber = ?";
    pst = conn.prepareStatement(checkSql);
    pst.setString(1, index);
    rs = pst.executeQuery();

    if (rs.next() && rs.getInt(1) > 0) {
        // If record exists, proceed with the update
        rs.close(); // Close the ResultSet before reusing the PreparedStatement

        String sql = "UPDATE testcricket SET playername = ?, role = ?, matches = ?, runs = ?, wickets = ?, jurscynubmer = ?, strikerate = ?, avarage = ?, best = ? WHERE indexnumber = ?";
        pst = conn.prepareStatement(sql);
        pst.setString(1, name);
        pst.setString(2, role);
        pst.setString(3, match);
        pst.setString(4, run);
        pst.setString(5, wicket);
        pst.setString(6, js);
        pst.setString(7, sr);
        pst.setString(8, avg);
        pst.setString(9, best);
        pst.setString(10, index);  // Set the indexnumber for the WHERE clause
        

        int rowsUpdated = pst.executeUpdate();
        if (rowsUpdated > 0) {
            JOptionPane.showMessageDialog(null, "Updated successfully");
        } else {
            JOptionPane.showMessageDialog(null, "Update failed: No matching record found");
        }
    } else {
        // No matching record found
        JOptionPane.showMessageDialog(null, "No matching record found " + index);
    }
} catch (SQLException e) {
    JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
} finally {
    try {
        if (rs != null) rs.close();
        if (pst != null) pst.close();
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, "Error closing resources: " + e.getMessage());
    }
}


}
    private void tindexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tindexActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tindexActionPerformed

    private void tbestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbestActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbestActionPerformed

    private void tnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tnameActionPerformed

    private void tmatchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tmatchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tmatchActionPerformed

    private void trunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trunActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_trunActionPerformed

    private void twicketsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twicketsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_twicketsActionPerformed

    private void tjurscyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tjurscyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tjurscyActionPerformed

    private void tstrikeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tstrikeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tstrikeActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        odi kg = new odi();
        kg.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        ttowenty dk = new ttowenty();
        dk.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void tavgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tavgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tavgActionPerformed

    private void moveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moveActionPerformed
           String player = tname.getText();
    String index = tindex.getText();
    String format = (String) tselect.getSelectedItem();
    int matches = Integer.parseInt(tmatch.getText());
    int runs = Integer.parseInt(trun.getText());
    int wickets = Integer.parseInt(twickets.getText());
    int juracy = Integer.parseInt(tjurscy.getText());
    int strike = Integer.parseInt(tstrike.getText());
    int avg = Integer.parseInt(tavg.getText());
    int best = Integer.parseInt(tbest.getText()); 
    
         try {
        String sql = "INSERT INTO testcricket (playername, indexnumber, role, matches, runs, wickets, jurscynubmer, strikerate, avarage, best) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
        PreparedStatement pst = conn.prepareStatement(sql);
        pst.setString(1, player);
        pst.setString(2, index);
        pst.setString(3, format);
        pst.setInt(4, matches);
        pst.setInt(5, runs);
        pst.setInt(6, wickets);
        pst.setInt(7, juracy);
        pst.setInt(8, strike);
        pst.setInt(9, avg);
        pst.setInt(10, best);
        
        pst.executeUpdate();
        
        JOptionPane.showMessageDialog(null, "Data inserted successfully!");
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, e.getMessage());
    }
         dataloadone();
    }//GEN-LAST:event_moveActionPerformed

    private void jButton27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton27ActionPerformed
        tabaledatat();
        dataloadone();
    }//GEN-LAST:event_jButton27ActionPerformed

    private void jButton28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton28ActionPerformed
                                         
                                        
        {                                        
 int check = JOptionPane.showConfirmDialog(null, "Do you want to delete?");
    if(check == JOptionPane.YES_OPTION){
        String ind = tindex.getText();
        try {
            String sql = "DELETE FROM testcricket WHERE indexnumber = ?";
            PreparedStatement pst = conn.prepareStatement(sql);
            pst.setString(1, ind);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Delete successfully!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "An error occurred: " + e.getMessage());
        }
    }
    }




    
     dataloadone();


    }//GEN-LAST:event_jButton28ActionPerformed

    private void tableMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_tableMouseEntered

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        
         testdata();
          dataloadone();
    }//GEN-LAST:event_tableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new test().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton move;
    private javax.swing.JTable table;
    private javax.swing.JTextField tavg;
    private javax.swing.JTextField tbest;
    private javax.swing.JTextField tindex;
    private javax.swing.JTextField tjurscy;
    private javax.swing.JTextField tmatch;
    private javax.swing.JTextField tname;
    private javax.swing.JTextField trun;
    private javax.swing.JComboBox<String> tselect;
    private javax.swing.JTextField tstrike;
    private javax.swing.JTextField twickets;
    // End of variables declaration//GEN-END:variables

    private static class PreparedStatment {

        public PreparedStatment() {
        }

        private void execute() {
            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        }
    }
}
